name: CI
on: [push, pull_request]
jobs:
  api:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: erp
          POSTGRES_PASSWORD: erp
          POSTGRES_DB: erp_ci
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U erp"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DATABASE_URL: postgresql://erp:erp@localhost:5432/erp_ci
      JWT_SECRET: test_ci_secret
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install API deps
        working-directory: apps/api
        run: npm ci
      - name: Prisma generate
        working-directory: apps/api
        run: npx prisma generate
      - name: Migrate CI DB
        working-directory: apps/api
        run: npx prisma migrate deploy
      - name: Build API
        working-directory: apps/api
        run: npm run build
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install Web deps
        working-directory: apps/web
        run: npm ci
      - name: Build Web
        working-directory: apps/web
        run: npm run build